//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string CardNumber { get; set; }
        public string AccountType { get; set; }
    }
}
